### ISSUE TITLE
Missing `chat_deontic` prompts?

### ISSUE THREAD

**Issue by namin** [gpoesia/certified-reasoning#4]
Hi,

The `lm_tool.py` file refers to files `prompts/chat_deontic_events.json` and `prompts/peano_chat_deontic_events`:
- https://github.com/gpoesia/certified-reasoning/blob/main/learning/lm_tool.py#L579
- https://github.com/gpoesia/certified-reasoning/blob/main/learning/lm_tool.py#L728

But the `prompts` directory only has `deontic_events` (no JSON) and `peano_deontic_events`.

Are some files missing?

Thank you.

**Comment by gpoesia** [comment]
Hi @namin!

Thanks for catching this! Sorry, these files were indeed missing. I juts [added them](https://github.com/gpoesia/certified-reasoning/commit/3fb7b3fb434aab6676d603651bc376801516ab9a) to the repository.

Seeing the two prompts side-by-side made me notice the guided prompt has a bit more information than the other one. Based on earlier attempts I don't think the unguided model will take too much advantage of this, but I'll run the unguided model with the guided prompt just to be sure!

**Comment by namin** [comment]
Great, thank you!
